### ISSUE TITLE
Use latest version of AJV to fix uri-js version 4.2.1 instead of 4.2.2

### ISSUE THREAD

**Issue by Vadorequest** [DivineGod/ajv-error-messages#3]
A bug with uri-js package has been fixed in ajv, but this lib doesn't use the latest ajv version and isn't using the latest version, and is therefore failing during compiling when using create-react-app.

https://github.com/epoberezkin/ajv/issues/833

Publishing a new version of jv-error-messages based on the lastest 6.x ajv version should fix this.

Or maybe my understanding is just wrong and it's because ajv-error-messages doesn't provide a build at all.

> Failed to minify the code from this file: 
> 
>         ./node_modules/ajv-error-messages/index.js:10:12 
>

**Comment by DivineGod** [comment]
Hi there!

Thank you for the report 

The dependency on ajv is only there for running tests and should affect the operation of this module.

This module does indeed not have a proper build as I made it only to be used from node.js initially
