### ISSUE TITLE
Validating Invalid Schema

### ISSUE THREAD

**Issue by asharali13** [DivineGod/ajv-error-messages#7]
```Javascript
{
  error:{
    obj:"Hey"
  }
}
```

upto best of my knowledge i guess it should thorw an error as Json should be like

```JSON
{
  "error":{
    "obj":"Hey"
  }
}
```

will be waiting for your reply.

**Comment by DivineGod** [comment]
Hi, This library is not responsible for any validation only transforming errors into a more manageable format.

`AJV` is also not a JSON deserializer and works on JavaScript objects.
